[package]
name = "hæstkuk"
version = "0.0.0"
authors = ["Jylam <jylam@lnxscene.org>"]

[dependencies]
    log = "0.4"
    env_logger = "0.6"
    minifb="*"
    image="*"
    cpal = "*"
    webp-animation = "*"
